### PR TITLE
adding example use case

### PR DESCRIPTION
**Pull request by crooksey**

### CODE REVIEW

**Comment by wichert** [comment]
This is awesome, thanks!

**Comment by crooksey** [comment]
No problem, you gave me a lot of help with setting this up over a year ago now and I have been using this on my REST api's ever since, it didn't take very long and hopefully it will make the use of JWT's clearer to other new users, as its quite an alien concept, when you compare it to a traditional permissions/security system.

**Comment by wichert** [comment]
FYI I've converted this to ReST and added it to the long_description so it shows up as part of the package description on pypi.

**Comment by crooksey** [comment]
OK no problem, did you want a hand with issue #4 with regards to extending the package to support audience spec?

**Comment by wichert** [comment]
@crooksey I would appreciate that very much :)

**Pull request merged**
